### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by link-hsu**
許修豪(discord: Link-Hsu)

http://44.218.113.169:3000/api/attractions?page=1

http://44.218.113.169:3000/api/attractions?page=0&keyword=劍潭

http://44.218.113.169:3000/api/attractions?page=0&keyword=北

http://44.218.113.169:3000/api/attractions/10

http://44.218.113.169:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Send proper error message for http://44.218.113.169:3000/api/attractions?page=5
2. http://44.218.113.169:3000/api/attractions?page=1&keyword=%E5%8C%97 should contain some data.
3. We cannot get all attracion data at once. Use SQL query to paging data directly.

Fix issues and re-request review from top right corner in this page.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I see no changes.

**Comment by link-hsu** [comment]
already recoding, THX!

http://44.218.113.169:3000/api/attractions?page=1

[http://44.218.113.169:3000/api/attractions?page=0&keyword=劍潭](http://44.218.113.169:3000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD)

[http://44.218.113.169:3000/api/attractions?page=0&keyword=北](http://44.218.113.169:3000/api/attractions?page=0&keyword=%E5%8C%97)

http://44.218.113.169:3000/api/attractions/10

http://44.218.113.169:3000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://44.218.113.169:3000/api/attractions?page=0&keyword=%E5%8C%97 and http://44.218.113.169:3000/api/attractions/10 are incorrect.
2. We cannot get all data at once and do pagination by our own code, even if in the situation of filtering by keyword.

Fix issues and re-request review.

**Comment by link-hsu** [comment]
不好意思麻煩老師幫我檢查那麼多次，希望這次有符合要求，感謝！

http://44.218.113.169:3000/api/attractions?page=1
http://44.218.113.169:3000/api/attractions?page=0&keyword=劍潭
http://44.218.113.169:3000/api/attractions?page=0&keyword=北
http://44.218.113.169:3000/api/attraction/10
http://44.218.113.169:3000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
