### PR TITLE
submit work for week 03

### PR DESCRIPTION
**Pull request by link-hsu**
彭彭老師好，我是修豪，下面是網頁連結，還請老師確認內容，感謝！

http://44.218.113.169:3000
http://44.218.113.169:3000/attraction/11

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Separating lines are 1px height with light grey color, align with design.
2. Image slider should extend to full width in mobile layout.

**Comment by link-hsu** [comment]
修改後連結如下，還麻煩老師確認
http://44.218.113.169:3000/
http://44.218.113.169:3000/attraction/11

**Review by cwpeng — CHANGES_REQUESTED** [review]
Separating lines are still 2px height.

**Comment by link-hsu** [comment]
和預期不同，又修改過了，再麻煩老師幫我看一下，感謝！
http://44.218.113.169:3000/
http://44.218.113.169:3000/attraction/11

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
